package d2skill

// CoverageRow is the engine coverage of one player skill of the Necromancer,
// Paladin, Sorceress or Druid (docs/skills-coverage-npsd.md is generated from
// this table by TestCoverageNPSD with D2_WRITE_COVERAGE=1).
//
// Status codes: F fully simulated (every effect of the skills.txt row has an
// engine counterpart), P partial (runs, but a documented part is approximated
// or missing), S stub (runs but the effect is only a state nothing reads), M
// missing (the pipeline refuses the cast), T passive (no cast; its stats feed
// other skills). Before is the state at the start of the branch feat/skills-npsd,
// After the state now. The statuses come from reading the handlers and the
// scenario logs, not from diffing every skill against the exe; the Note column
// says what was verified in the exe and what is approximated.
type CoverageRow struct {
	ID            int
	Name, Class   string
	DoFunc        string
	Before, After string
	Note          string
}

// CoverageNPSD lists all 120 skills of the four classes.
var CoverageNPSD = []CoverageRow{
	{66, "Amplify Damage", "Necromancer", "30", "F", "F", "state with damageresist -100 on enemies in range"},
	{67, "Teeth", "Necromancer", "8", "F", "F", "missile fan (do 8)"},
	{68, "Bone Armor", "Necromancer", "18", "F", "F", "absorb state, Director HeroDefense hook"},
	{69, "Skeleton Mastery", "Necromancer", "-", "T", "T", "feeds the Raise Skeleton order (hp, damage)"},
	{70, "Raise Skeleton", "Necromancer", "31", "F", "F", "d2summon stats, roster limits"},
	{71, "Dim Vision", "Necromancer", "30", "S", "F", "before: state only; now forces monster AI state 10 (blind)"},
	{72, "Weaken", "Necromancer", "30", "F", "F", "state with damageresist / damage stats"},
	{73, "Poison Dagger", "Necromancer", "32", "F", "F", "melee + poison stream"},
	{74, "Corpse Explosion", "Necromancer", "55", "P", "P", "level scale vs corpse added (verified 0x5c2c60); radius halving (ln34+1)/2 and calc3 element not ported"},
	{75, "Clay Golem", "Necromancer", "56", "F", "F", "golem order, one at a time"},
	{76, "Iron Maiden", "Necromancer", "30", "F", "F", "reflect via afterHit"},
	{77, "Terror", "Necromancer", "30", "F", "F", "flee state"},
	{78, "Bone Wall", "Necromancer", "60", "P", "P", "wall pieces as blocking monsters; exe piece layout (SKILL_SpawnBonePrisonWalls offsets) approximated"},
	{79, "Golem Mastery", "Necromancer", "-", "T", "T", "feeds golem orders"},
	{80, "Raise Skeletal Mage", "Necromancer", "31", "P", "P", "raised, but the mage melees (no ranged attack AI)"},
	{81, "Confuse", "Necromancer", "61", "S", "F", "before: state only; now forces confuse (list 9, mode 3)"},
	{82, "Life Tap", "Necromancer", "30", "F", "F", "heal via afterHit"},
	{83, "Poison Explosion", "Necromancer", "63", "P", "P", "area poison hit instead of the poisonexplosioncloud sub-missile fan"},
	{84, "Bone Spear", "Necromancer", "-", "F", "F", "generic missile path"},
	{85, "BloodGolem", "Necromancer", "56", "P", "P", "golem; life-leech-to-owner behaviour not checked against the exe"},
	{86, "Attract", "Necromancer", "59", "S", "F", "before: state only; now forces attract (list 9, alignment 1)"},
	{87, "Decrepify", "Necromancer", "30", "F", "F", "state, slow and damage stats"},
	{88, "Bone Prison", "Necromancer", "62", "P", "P", "ring of 8 pieces (exe uses a 12 cell offset table 0x6e45e0/0x6e4610 and links pieces to a leader)"},
	{89, "Summon Resist", "Necromancer", "-", "T", "T", ""},
	{90, "IronGolem", "Necromancer", "57", "M", "P", "do 57 added as a golem order; the consumed item and its derived stats are not simulated"},
	{91, "Lower Resist", "Necromancer", "30", "F", "F", "state with resist stats"},
	{92, "Poison Nova", "Necromancer", "22", "F", "F", "nova missile ring (do 22)"},
	{93, "Bone Spirit", "Necromancer", "10", "F", "F", "homing missile (do 10)"},
	{94, "FireGolem", "Necromancer", "56", "P", "P", "golem; the fire absorb / damage aura stats come from the order only"},
	{95, "Revive", "Necromancer", "58", "P", "P", "uses the corpse type; level cap + life scaling to caster level added (verified 0x5c35a0); life roll at the corpse level not ported"},
	{96, "Sacrifice", "Paladin", "64", "F", "F", "self damage + strike"},
	{97, "Smite", "Paladin", "150", "P", "P", "shield bash damage; knockback/stun not simulated"},
	{98, "Might", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{99, "Prayer", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{100, "Resist Fire", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{101, "Holy Bolt", "Paladin", "-", "P", "P", "bolt damages undead; healing of allies not simulated"},
	{102, "Holy Fire", "Paladin", "66", "F", "F", "damage aura (do 66)"},
	{103, "Thorns", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{104, "Defiance", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{105, "Resist Cold", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{106, "Zeal", "Paladin", "13", "F", "F", "multi hit"},
	{107, "Charge", "Paladin", "67", "P", "P", "rush + strike, movement approximated"},
	{108, "Blessed Aim", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{109, "Cleansing", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{110, "Resist Lightning", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{111, "Vengeance", "Paladin", "2", "F", "F", "elemental melee"},
	{112, "Blessed Hammer", "Paladin", "73", "P", "P", "missile without the spiral movement"},
	{113, "Concentration", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{114, "Holy Freeze", "Paladin", "81", "F", "F", "enemy aura, cold damage + slow"},
	{115, "Vigor", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{116, "Conversion", "Paladin", "79", "M", "P", "do 79 added (roll, state, level/life scale, charm AI); boss exclusion U"},
	{117, "Holy Shield", "Paladin", "18", "F", "F", "self state (do 18)"},
	{118, "Holy Shock", "Paladin", "66", "F", "F", "damage aura"},
	{119, "Sanctuary", "Paladin", "66", "P", "P", "damages all enemies, exe damages undead only and knocks back"},
	{120, "Meditation", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{121, "Fist of the Heavens", "Paladin", "80", "P", "P", "bolt at the aim; the follow-up holy bolts are not simulated"},
	{122, "Fanaticism", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{123, "Conviction", "Paladin", "66", "F", "F", "enemy resist aura"},
	{124, "Redemption", "Paladin", "82", "P", "P", "corpse consumption heals; exe radius / cost rules approximated"},
	{125, "Salvation", "Paladin", "65", "F", "F", "friendly aura (do 65): stats re-applied every pulse"},
	{36, "Fire Bolt", "Sorceress", "-", "F", "F", "generic missile path"},
	{37, "Warmth", "Sorceress", "-", "T", "T", ""},
	{38, "Charged Bolt", "Sorceress", "17", "F", "F", "do 17"},
	{39, "Ice Bolt", "Sorceress", "-", "F", "F", "generic missile path"},
	{40, "Frozen Armor", "Sorceress", "18", "F", "F", "do 18 self state with chill on melee attackers"},
	{41, "Inferno", "Sorceress", "19", "F", "F", "stream (do 19)"},
	{42, "Static Field", "Sorceress", "20", "F", "F", "do 20"},
	{43, "Telekinesis", "Sorceress", "21", "M", "P", "do 21 added: damage on a targeted monster; item pickup and object use are not simulated"},
	{44, "Frost Nova", "Sorceress", "22", "F", "F", "do 22"},
	{45, "Ice Blast", "Sorceress", "-", "F", "F", "generic missile path"},
	{46, "Blaze", "Sorceress", "23", "F", "F", ""},
	{47, "Fire Ball", "Sorceress", "-", "F", "F", "generic missile path"},
	{48, "Nova", "Sorceress", "22", "F", "F", "do 22"},
	{49, "Lightning", "Sorceress", "-", "F", "F", "generic missile path"},
	{50, "Shiver Armor", "Sorceress", "18", "F", "F", "do 18 self state with chill on melee attackers"},
	{51, "Fire Wall", "Sorceress", "24", "F", "F", ""},
	{52, "Enchant", "Sorceress", "25", "F", "F", ""},
	{53, "Chain Lightning", "Sorceress", "26", "F", "F", ""},
	{54, "Teleport", "Sorceress", "27", "P", "F", "levels.txt Teleport flag (0 refuse, 2 no walls) added (verified 0x5c84d0)"},
	{55, "Glacial Spike", "Sorceress", "-", "F", "F", "generic missile path"},
	{56, "Meteor", "Sorceress", "28", "P", "P", "SRVDO_028 creates meteorcenter (hit 14: area damage + meteorfire burning ground with its own fire damage columns); bodies read"},
	{57, "Thunder Storm", "Sorceress", "29", "P", "P", "strikes the nearest enemy, no random targets"},
	{58, "Energy Shield", "Sorceress", "23", "P", "P", "mana absorb ratio passed unverified"},
	{59, "Blizzard", "Sorceress", "28", "P", "P", "SRVDO_028 creates blizzardcenter; SrvDoFunc 10 drops blizzard1 shards (calc1 radius, calc2 period); bodies read; blizzard1 hits only its own cell (missile Size not modelled)"},
	{60, "Chilling Armor", "Sorceress", "18", "F", "F", "do 18 self state with chill on melee attackers"},
	{61, "Fire Mastery", "Sorceress", "-", "T", "T", ""},
	{62, "Hydra", "Sorceress", "144", "M", "P", "do 144 added: 3 stationary fire shooters in the exe triangle; hydra AI timing U"},
	{63, "Lightning Mastery", "Sorceress", "-", "T", "T", ""},
	{64, "Frozen Orb", "Sorceress", "-", "P", "P", "STAND-IN: do 15 bolt spiral + hit 29 16-way nova ring (d2missile/orb.go, bodies not read); frozenorbnova do 16 is plain flight"},
	{65, "Cold Mastery", "Sorceress", "-", "T", "T", ""},
	{221, "Raven", "Druid", "114", "P", "F", "summon level (calc2) now set through the order; stats from d2summon + MonLvl AC/AR (verified 0x5c2850)"},
	{222, "Plague Poppy", "Druid", "115", "M", "P", "do 115 added: vine shooter with calc1 life, calc2 level"},
	{223, "Wearwolf", "Druid", "116", "P", "P", "timed form state; the form attack skills are not rebound"},
	{224, "Shape Shifting", "Druid", "-", "T", "T", ""},
	{225, "Firestorm", "Druid", "117", "P", "P", "fire bursts in a line approximated"},
	{226, "Oak Sage", "Druid", "119", "P", "P", "totem aura as a state; stats follow the order"},
	{227, "Summon Spirit Wolf", "Druid", "119", "P", "F", "summon level (calc2) + MonLvl AC/AR now applied; resist / armor / damage stats from the order"},
	{228, "Wearbear", "Druid", "116", "P", "P", "timed form state"},
	{229, "Molten Boulder", "Druid", "-", "P", "P", "emerge (hit 48) -> boulder (do 6 trail, hit 47) -> moltenboulderfirepath fire; bodies read, hit 47 monster-class bit UNVERIFIED"},
	{230, "Arctic Blast", "Druid", "19", "F", "F", "stream (do 19)"},
	{231, "Cycle of Life", "Druid", "115", "M", "P", "do 115 added (attack only; the corpse cycler heal is not simulated)"},
	{232, "Feral Rage", "Druid", "120", "P", "P", "stacking state with leech stats; exe leech not applied"},
	{233, "Maul", "Druid", "120", "P", "P", "stacking state, stun on hit"},
	{234, "Eruption", "Druid", "28", "P", "P", "SRVDO_028 creates erruption center; SrvDoFunc 25 scatter (calc1/calc2) read; the crack and fire sub missiles are not read"},
	{235, "Cyclone Armor", "Druid", "18", "F", "F", "do 18"},
	{236, "Heart of Wolverine", "Druid", "119", "P", "P", "totem aura as a state"},
	{237, "Summon Fenris", "Druid", "119", "P", "F", "summon level (calc2) + MonLvl AC/AR now applied"},
	{238, "Rabies", "Druid", "121", "P", "P", "poison bite; the spreading contagion of the exe is not ported"},
	{239, "Fire Claws", "Druid", "2", "F", "F", "do 2 melee with fire"},
	{240, "Twister", "Druid", "118", "P", "P", "missile chain approximated"},
	{241, "Vines", "Druid", "115", "M", "P", "do 115 added (attack only; the vine cycler is not simulated)"},
	{242, "Hunger", "Druid", "122", "M", "F", "do 122 added: melee roll, calc1 damage percent, life and mana steal (verified 0x5c5f40)"},
	{243, "Shock Wave", "Druid", "8", "P", "P", "missile fan with stun"},
	{244, "Volcano", "Druid", "123", "P", "P", "SRVDO_123 creates volcano with a random data byte; SrvDoFunc 28 lobs debris, hit 51 spawns the fire; bodies read"},
	{245, "Tornado", "Druid", "118", "P", "P", "missile without the wander path"},
	{246, "Spirit of Barbs", "Druid", "119", "P", "P", "totem aura as a state"},
	{247, "Summon Grizzly", "Druid", "119", "P", "F", "summon level (calc2) + MonLvl AC/AR now applied"},
	{248, "Fury", "Druid", "13", "F", "F", "multi hit (do 13)"},
	{249, "Armageddon", "Druid", "124", "P", "P", "random meteors approximated"},
	{250, "Hurricane", "Druid", "124", "P", "P", "area ticks"},
}
