#!/bin/zsh
# The class matrix: every class through the full Act 1 to 5 playthrough chain, one scenario at a time.
#
#   OD2_VERIFY_NIGHTLY=1 scripts/verify_classes.sh [options]
#
# For each class (amazon sorc necro paladin barb druid assassin; OD2_HERO=<class>, the level 94 heroes of
# d2core/d2hero/herogen, 9b a fresh level 1 hero of the class) it runs the scenarios
#   9b-act1-playthrough  9e-act2-playthrough  9g-act3-playthrough  9h-act45-playthrough  9i-act5-caves-playthrough
# each through scripts/verify.sh (OD2_VERIFY_ONLY=<scenario>, SKIP_UNIT=1, muted, the sped-up game clock the scenarios set), logs PASS / FAIL, the
# wall-clock runtime, the deaths of the hero and the first anomaly of every run to a table, and writes docs/class-matrix.md.
#
# It is SLOW (7 classes x about 35 to 45 minutes, so 4 to 5 hours with one game at a time) and NOT part of
# verify.sh / verify_parallel.sh: it only runs with OD2_VERIFY_NIGHTLY=1 (without it the script says so and exits 0).
# It refuses to start while a verify_parallel.sh is running (OD2_CLASS_MATRIX_FORCE=1 overrides).
#
# Options:
#   --classes a,b,c        only these classes (default: all seven; or OD2_CLASSES)
#   --scenarios s1,s2      only these scenario file names (default: the five above; or OD2_CLASS_SCENARIOS)
#   --resume               keep the results of an earlier run and skip the (class, scenario) pairs that passed
#   --dry-run              print what would run and exit (no gate, no game)
#   --render               only regenerate docs/class-matrix.md from the results table (no gate, no game)
#   --no-doc               do not write docs/class-matrix.md
# Environment: OD2_CLASS_MATRIX_VERIFY (the verify command, default ./scripts/verify.sh), OD2_CLASS_MATRIX_DOC (default docs/class-matrix.md), OD2_CLASS_MATRIX_DIR (default /tmp/od2-class-matrix: results.tsv, per-run output and game logs),
# D2_TABLES, D2S_SAMPLE_BODY, D2S_SAMPLE_BODY_JSON (defaults: the usual places under $HOME).
set -u
cd "${0:A:h}/.." || exit 1

classes=(amazon sorc necro paladin barb druid assassin)
all_classes=($classes)
[ -n "${OD2_CLASSES:-}" ] && classes=(${(s:,:)OD2_CLASSES})
scenarios=(9b-act1-playthrough 9e-act2-playthrough 9g-act3-playthrough 9h-act45-playthrough 9i-act5-caves-playthrough)
[ -n "${OD2_CLASS_SCENARIOS:-}" ] && scenarios=(${(s:,:)OD2_CLASS_SCENARIOS})
work=${OD2_CLASS_MATRIX_DIR:-/tmp/od2-class-matrix}
doc=${OD2_CLASS_MATRIX_DOC:-docs/class-matrix.md}
dry=0 render_only=0 resume=0 write_doc=1

while [ $# -gt 0 ]; do
  case "$1" in
    --classes) classes=(${(s:,:)2}); shift 2 ;;
    --scenarios) scenarios=(${(s:,:)2}); shift 2 ;;
    --resume) resume=1; shift ;;
    --dry-run) dry=1; shift ;;
    --render) render_only=1; shift ;;
    --no-doc) write_doc=0; shift ;;
    -h|--help) sed -n '2,/^set -u/p' "$0" | sed '$d'; exit 0 ;;
    *) echo "verify_classes.sh: unknown option $1 (see --help)" >&2; exit 2 ;;
  esac
done

typeset -A label
label=(
  9b-act1-playthrough "9b Act 1 (fresh)" 9e-act2-playthrough "9e Act 2" 9g-act3-playthrough "9g Act 3"
  9h-act45-playthrough "9h Acts 4+5" 9i-act5-caves-playthrough "9i Act 5 caves" 9i-act2-full "9i Act 2 full"
  9g-act3-durance "9g Durance" 9d-act1-sample-hero "9d Act 1 (94)"
)

results=$work/results.tsv
verify_cmd=${OD2_CLASS_MATRIX_VERIFY:-./scripts/verify.sh}   # a fake one in scripts/test_verify_classes.sh
tab=$'\t'

# ---------------------------------------------------------------------------------------------------------------
# docs/class-matrix.md from the results table (class, scenario, result, seconds, deaths, first anomaly, date, commit)
# ---------------------------------------------------------------------------------------------------------------
render_doc() {
  local labels="" s
  for s in $scenarios; do labels+="${label[$s]:-$s},"; done
  local when sha n
  sha=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
  when=$(date '+%Y-%m-%d %H:%M')
  n=0; [ -s $results ] && n=$(wc -l < $results | tr -d ' ')
  {
    echo "# Class playthrough matrix"
    echo
    echo "Generated by \`scripts/verify_classes.sh\` (nightly: \`OD2_VERIFY_NIGHTLY=1\`; not part of \`verify_parallel.sh\`). Every class plays the"
    echo "Act 1 to 5 chain one scenario at a time through \`scripts/verify.sh\` with \`OD2_HERO=<class>\`: the level 94 hero of"
    echo "\`d2core/d2hero/herogen\` (\`scripts/verify.d/lib/hero.sh\`), except 9b, which starts a brand new level 1 hero of the class."
    echo "The scripted fights cast the class' left skill (\`d2game/d2gamescreen/fightskill.go\`), real combat, no god mode."
    echo
    if [ $n -eq 0 ]; then
      echo "**Not run yet.** $(date '+%Y-%m-%d'), commit \`$sha\`: the matrix is empty until the nightly run has been done."
    else
      echo "Last update $when, commit \`$sha\`, $n run(s) in the table. A cell is *result runtime deaths*:"
      echo "\`PASS\` / \`PASS*\` (passed on the second attempt that verify.sh makes) / \`FAIL\`, wall clock, deaths of the hero (\`d\`)."
    fi
    echo
    awk -F'\t' -v classes="${(j:,:)all_classes}" -v scns="${(j:,:)scenarios}" -v labels="$labels" '
      function fmt(s,   h, m, sec) {
        if (s == "" || s == "-") return "-"
        h = int(s / 3600); m = int((s % 3600) / 60); sec = s % 60
        if (h > 0) return sprintf("%dh%02dm", h, m)
        return sprintf("%dm%02ds", m, sec)
      }
      BEGIN { nc = split(classes, C, ","); ns = split(scns, S, ","); nl = split(labels, L, ",") }
      { k = $1 SUBSEP $2; res[k] = $3; secs[k] = $4; dead[k] = $5; anom[k] = $6 }
      END {
        printf "| class |"; for (j = 1; j <= ns; j++) printf " %s |", L[j]; printf " total | deaths | passed |\n"
        printf "|---|"; for (j = 1; j <= ns; j++) printf "---|"; printf "---|---|---|\n"
        for (i = 1; i <= nc; i++) {
          tot = 0; td = 0; pass = 0; ran = 0
          printf "| %s |", C[i]
          for (j = 1; j <= ns; j++) {
            k = C[i] SUBSEP S[j]
            if (!(k in res)) { printf " - |"; continue }
            ran++; tot += secs[k]
            if (dead[k] ~ /^[0-9]+$/) td += dead[k]
            if (res[k] ~ /^PASS/) pass++
            printf " %s %s d%s |", res[k], fmt(secs[k]), dead[k]
          }
          printf " %s | %d | %d/%d |\n", (ran ? fmt(tot) : "-"), td, pass, ns
        }
        print ""
        print "## First anomaly of every run"
        print ""
        print "| class | scenario | result | runtime | deaths | first anomaly |"
        print "|---|---|---|---|---|---|"
        any = 0
        for (i = 1; i <= nc; i++) for (j = 1; j <= ns; j++) {
          k = C[i] SUBSEP S[j]
          if (!(k in res)) continue
          any = 1
          a = anom[k]; if (a == "") a = "none"
          printf "| %s | %s | %s | %s | %s | %s |\n", C[i], S[j], res[k], fmt(secs[k]), dead[k], a
        }
        if (!any) print "| - | - | - | - | - | not run |"
      }' $results 2>/dev/null || true
    echo
    echo "## How to run"
    echo
    echo '```'
    echo "OD2_VERIFY_NIGHTLY=1 scripts/verify_classes.sh                  # all seven classes, five scenarios each, one game at a time"
    echo "OD2_VERIFY_NIGHTLY=1 scripts/verify_classes.sh --classes necro,amazon --resume"
    echo "scripts/verify_classes.sh --dry-run                             # what would run"
    echo "scripts/verify_classes.sh --render                              # regenerate this file from the results table"
    echo '```'
    echo
    echo "Plan and time: 7 classes x 5 scenarios, about 35 to 45 minutes per class with the sped-up game clock (x3 to x4) of the scenarios and one game window,"
    echo "so 4 to 5 hours for the whole matrix; the table and the per-run logs are kept in \`\$OD2_CLASS_MATRIX_DIR\` (default"
    echo "\`/tmp/od2-class-matrix\`: \`results.tsv\`, \`<class>.<scenario>.out\`, \`<class>.<scenario>.log.txt\`). \`--resume\` continues an"
    echo "interrupted night. The anomaly column is the first \`FAIL:\` line of verify.sh, else the first error, warning, give-up or"
    echo "dropped-skill line of the game log."
  } > $doc.new && mv $doc.new $doc
  echo "wrote $doc"
}

if [ $render_only -eq 1 ]; then
  mkdir -p $work; touch $results
  render_doc
  exit 0
fi

echo "class matrix: ${#classes} class(es) x ${#scenarios} scenario(s): ${classes} / ${scenarios}"

if [ $dry -eq 1 ]; then
  for c in $classes; do for s in $scenarios; do
    echo "OD2_HERO=$c OD2_VERIFY_ONLY=$s SKIP_UNIT=1 scripts/verify.sh"
  done; done
  echo "(dry run: nothing started; results would go to $results, then $doc)"
  exit 0
fi

if [ -z "${OD2_VERIFY_NIGHTLY:-}" ]; then
  echo "verify_classes.sh: SKIPPED. The class matrix is the nightly, slow run (7 classes x 5 scenarios, 4 to 5 hours): set OD2_VERIFY_NIGHTLY=1 to run it."
  exit 0
fi

if pgrep -f verify_parallel.sh >/dev/null && [ -z "${OD2_CLASS_MATRIX_FORCE:-}" ]; then
  echo "verify_classes.sh: a verify_parallel.sh is running; wait for it (or set OD2_CLASS_MATRIX_FORCE=1)." >&2
  exit 3
fi

export D2_TABLES=${D2_TABLES:-$HOME/git/d2-tables}
export D2S_SAMPLE_BODY=${D2S_SAMPLE_BODY:-$HOME/git/nokka-d2s-ref/examples/nokkasorc}
export D2S_SAMPLE_BODY_JSON=${D2S_SAMPLE_BODY_JSON:-$HOME/git/nokka-d2s-ref/examples/nokkasorc.json}
for v in D2_TABLES D2S_SAMPLE_BODY D2S_SAMPLE_BODY_JSON; do
  [ -e "${(P)v}" ] || { echo "verify_classes.sh: $v=${(P)v} does not exist" >&2; exit 1; }
done

mkdir -p $work
[ $resume -eq 1 ] || : > $results
touch $results

# one run at a time on this results folder
lock=$work/lock
if [ -e $lock ] && kill -0 "$(cat $lock 2>/dev/null)" 2>/dev/null; then
  echo "verify_classes.sh: another matrix run (pid $(cat $lock)) uses $work" >&2
  exit 3
fi
echo $$ > $lock
trap 'rm -f $lock' EXIT
trap 'rm -f $lock; exit 130' INT
trap 'rm -f $lock; exit 143' TERM

# the first thing that went wrong in a run: a FAIL line of verify.sh, else a reaped game, else the first error,
# warning, give-up or dropped skill of the game log
first_anomaly() {
  local out=$1 logtxt=$2 a=""
  a=$(grep -m1 -E '^(FAIL|REAPED|VERIFY ABORTED|BUILD FAILED|SKIP|SOME CHECKS)' $out 2>/dev/null)
  if [ -z "$a" ] && [ -s "$logtxt" ]; then
    a=$(grep -E '\[(ERROR|WARNING)\]|panic|KILL giving up|KILL left skill|DEATH hero=|Unknown tile' $logtxt \
        | grep -v "skipping missing" | head -1)
  fi
  # one table cell: no tabs, no pipes, no ANSI, bounded
  print -r -- "$a" | sed 's/\x1b\[[0-9;]*m//g' | tr -d '\t|' | cut -c1-200
}

run_one() {
  local cls=$1 scn=$2 tf out start end rc res secs deaths tmpd logtxt anomaly
  tf=$work/tmpdir.$cls.$scn; out=$work/$cls.$scn.out; rm -f $tf
  echo "== $(date '+%H:%M:%S') $cls / $scn"
  start=$(date +%s)
  OD2_HERO=$cls OD2_VERIFY_ONLY=$scn SKIP_UNIT=1 OD2_VERIFY_TMPFILE=$tf ${=verify_cmd} > $out 2>&1
  rc=$?
  end=$(date +%s); secs=$((end - start))

  res=FAIL
  if [ $rc -eq 0 ] && grep -q "ALL CHECKS PASSED" $out && grep -q "^SCENARIOS RUN: 1" $out; then
    res=PASS
    grep -q "^RETRY:" $out && res="PASS*"
  fi

  tmpd=""; [ -s $tf ] && tmpd=$(cat $tf)
  logtxt=$work/$cls.$scn.log.txt; rm -f $logtxt
  [ -n "$tmpd" ] && [ -s $tmpd/$scn.log.txt ] && cp $tmpd/$scn.log.txt $logtxt
  deaths="?"; [ -s $logtxt ] && deaths=$(grep -c "DEATH hero=" $logtxt)
  anomaly=$(first_anomaly $out $logtxt)

  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$cls" "$scn" "$res" "$secs" "$deaths" "$anomaly" >> $results
  echo "   $res in ${secs}s, deaths=$deaths${anomaly:+, first anomaly: $anomaly}"
  # the scratch folder of verify.sh holds the game binary and screenshots; the logs are kept above
  case "$tmpd" in /tmp/od2-verify.*) rm -rf "$tmpd" ;; esac
}

for cls in $classes; do
  for scn in $scenarios; do
    if [ $resume -eq 1 ] && grep -qE "^$cls${tab}$scn${tab}PASS" $results; then
      echo "== $cls / $scn: passed earlier, skipped (--resume)"
      continue
    fi
    # one row per pair: drop an older row of the same pair (a resumed run replaces a FAIL)
    grep -vE "^$cls${tab}$scn${tab}" $results > $results.tmp; mv $results.tmp $results
    run_one $cls $scn
    [ $write_doc -eq 1 ] && render_doc >/dev/null
  done
done

[ $write_doc -eq 1 ] && render_doc
echo
echo "CLASS MATRIX: $(grep -c "${tab}PASS" $results) of $(wc -l < $results | tr -d ' ') runs passed (table: $results)"
if grep -q "${tab}FAIL${tab}" $results; then exit 1; fi
exit 0
